In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
df1=pd.read_csv('job-post_data.csv')
df1

,Job_title,Location,Work_environment,Work_time,Experience_level,Description,Company_name
0,Quality Assurance Engineer (For TechForing Ltd...,"Dhaka, Bangladesh",On-site,Full-time,Executive,TechForing Ltd is looking for Quality Assuranc...,Bdjobs.com
1,Head-end system Engineer (For Oculin Tech BD L...,"Dhaka, Bangladesh",On-site,Full-time,Executive,Oculin Tech BD Ltd. is looking for Head-end sy...,Bdjobs.com
2,"Senior Software Engineer ( .NET , React / Blaz...","Dhaka, Bangladesh",On-site,Full-time,Executive,Link3 Technologies Limited is looking for Seni...,Bdjobs.com
3,System Engineer - For International Office Mac...,"Dhaka, Bangladesh",On-site,Full-time,Mid-Senior level,International Office Machines Ltd is looking f...,Bdjobs.com
4,OSS Engineer,"Dhaka, Bangladesh",On-site,Full-time,Mid-Senior level,Responsibilities：\n1. Be responsible for OSS t...,ZTE Corporation
...,...,...,...,...,...,...,...
794,Back End Developer,APAC,Remote,Contract,Mid-Senior level,"KEY RESPONSIBILITIES \n● Build, deploy, and ma...",Andela
795,Web Developer - For Ganitik Tech Limited (Job ...,"Dinājpur, Rajshahi, Bangladesh",On-site,Full-time,Entry level,Ganitik Tech Limited is looking for Web Develo...,Bdjobs.com
796,React Native Developer,"Dhaka, Dhaka, Bangladesh","$830/month - $1,670/month",Remote,Full-time,Wing Assistant is seeking an experienced React...,Wing Assistant
797,Node.js Developer,"Dhaka, Dhaka, Bangladesh",On-site,Full-time,Mid-Senior level,Company Description\n\nWe are seeking a talent...,Flyte Solutions Ltd.
798,Full-Stack JavaScript Engineer (Angular),"Dhaka, Dhaka, Bangladesh",On-site,Full-time,NaN,Job Context\nWe are a technology startup to di...,Mind Orbital

In [27]:
df2=pd.read_csv('job-post_data2.csv')
df2

,Job_title,Location,Work_environment,Work_time,Experience_level,Description,Company_name
0,"Intern (Paid), Walton Mobile - For Walton Digi...","Gazipur District, Dhaka, Bangladesh",On-site,Internship,NaN,Walton Digi-Tech Industries Limited is looking...,Bdjobs.com
1,Engineer - For EDUAID- Job ID - 1293905,"Dhaka, Bangladesh",On-site,Full-time,NaN,EDUAID is looking for Engineer\n\nJob Descript...,Bdjobs.com
2,Officer / Sr. Officer (HR) - For A reputed Cor...,"Dhaka, Bangladesh",On-site,Full-time,NaN,A reputed Corporate Hospital is looking for Of...,Bdjobs.com
3,Associate - Day Shift - For Quantanite Banglad...,"Dhaka, Bangladesh",On-site,Full-time,NaN,Quantanite Bangladesh Limited is looking for A...,Bdjobs.com
4,AI & Data Science Training & Intership,APJ,Remote,Internship,NaN,"Refonte Infini is a global leader in IT, renow...",Refonte Learning
...,...,...,...,...,...,...,...
739,MIS and Documentation Officer (For Proyas Mano...,"Chapai Nawabganj District, Rajshahi, Bangladesh",On-site,Full-time,NaN,Proyas Manobik Unnayan Society is looking for ...,Bdjobs.com
740,Sales Analyst - For Walton Hi-Tech Industries ...,"Dhaka, Bangladesh",On-site,Internship,NaN,Walton Hi-Tech Industries PLC. is looking for ...,Bdjobs.com
741,"Full-Stack Web Developer (Laravel, React.js/Vu...","Dhaka, Bangladesh",On-site,Full-time,NaN,Arialkhan.com is looking for Full-Stack Web De...,Bdjobs.com
742,Sr. Executive / Asst. Manager - Sales & Market...,"Dhaka, Bangladesh",On-site,Full-time,NaN,Standard Design & Development Ltd. is looking ...,Bdjobs.com
743,Service Engineer - For Executive Machines Ltd ...,"Dhaka, Bangladesh",On-site,Full-time,NaN,Executive Machines Ltd is looking for Service ...,Bdjobs.com

In [28]:
df=pd.concat([df1,df2],axis=0)

# preprocessing

In [29]:
df.isnull().sum()

Job_title             0
Location              0
Work_environment      4
Work_time            18
Experience_level    835
Description           0
Company_name          0
dtype: int64

In [30]:
df.duplicated().sum()

326

In [31]:
import re

In [32]:
# Filter Job title - which is post from bdjobs.com
pattern=r'-\s*For|\(For'
def filter_job_title(dataframe):
    job_title=[]
    company_name=[]
    for index,row in dataframe.iterrows():
        data=row['Job_title']
        entry=re.split(pattern, data)
        if entry[1:]:
            job_title.append(entry[0])
            company_name.append(entry[1] )
        else:
            job_title.append(entry[0])
            company_name.append(row['Company_name'])
    dataframe['Job_title']=job_title
    dataframe['Company_name']=company_name

In [33]:
filter_job_title(df)
df.head()

,Job_title,Location,Work_environment,Work_time,Experience_level,Description,Company_name
0,Quality Assurance Engineer,"Dhaka, Bangladesh",On-site,Full-time,Executive,TechForing Ltd is looking for Quality Assuranc...,TechForing Ltd) - Job ID : 1283291
1,Head-end system Engineer,"Dhaka, Bangladesh",On-site,Full-time,Executive,Oculin Tech BD Ltd. is looking for Head-end sy...,Oculin Tech BD Ltd.) - Job ID : 1284316
2,"Senior Software Engineer ( .NET , React / Blaz...","Dhaka, Bangladesh",On-site,Full-time,Executive,Link3 Technologies Limited is looking for Seni...,Link3 Technologies Limited)-Job ID: 1284202
3,System Engineer,"Dhaka, Bangladesh",On-site,Full-time,Mid-Senior level,International Office Machines Ltd is looking f...,International Office Machines Ltd- Job ID - 1...
4,OSS Engineer,"Dhaka, Bangladesh",On-site,Full-time,Mid-Senior level,Responsibilities：\n1. Be responsible for OSS t...,ZTE Corporation

In [34]:
# Filter Company Name -remove job ID
pattern=r'\)|\(|-\s*Job'
def filter_company(dataframe):
    name=[]
    for data in dataframe['Company_name']:
        name.append( re.split(pattern,data)[0] )
    dataframe['Company_name']=name

In [35]:
filter_company(df)
df.head(5)

,Job_title,Location,Work_environment,Work_time,Experience_level,Description,Company_name
0,Quality Assurance Engineer,"Dhaka, Bangladesh",On-site,Full-time,Executive,TechForing Ltd is looking for Quality Assuranc...,TechForing Ltd
1,Head-end system Engineer,"Dhaka, Bangladesh",On-site,Full-time,Executive,Oculin Tech BD Ltd. is looking for Head-end sy...,Oculin Tech BD Ltd.
2,"Senior Software Engineer ( .NET , React / Blaz...","Dhaka, Bangladesh",On-site,Full-time,Executive,Link3 Technologies Limited is looking for Seni...,Link3 Technologies Limited
3,System Engineer,"Dhaka, Bangladesh",On-site,Full-time,Mid-Senior level,International Office Machines Ltd is looking f...,International Office Machines Ltd
4,OSS Engineer,"Dhaka, Bangladesh",On-site,Full-time,Mid-Senior level,Responsibilities：\n1. Be responsible for OSS t...,ZTE Corporation

In [36]:
df.duplicated().sum()

326

In [37]:
# remove duplicate value
df.drop_duplicates(inplace=True)

In [38]:
df.shape

(1217, 7)

In [39]:
df.to_csv('processed_job-post_data.csv',index=False)

In [40]:
df

,Job_title,Location,Work_environment,Work_time,Experience_level,Description,Company_name
0,Quality Assurance Engineer,"Dhaka, Bangladesh",On-site,Full-time,Executive,TechForing Ltd is looking for Quality Assuranc...,TechForing Ltd
1,Head-end system Engineer,"Dhaka, Bangladesh",On-site,Full-time,Executive,Oculin Tech BD Ltd. is looking for Head-end sy...,Oculin Tech BD Ltd.
2,"Senior Software Engineer ( .NET , React / Blaz...","Dhaka, Bangladesh",On-site,Full-time,Executive,Link3 Technologies Limited is looking for Seni...,Link3 Technologies Limited
3,System Engineer,"Dhaka, Bangladesh",On-site,Full-time,Mid-Senior level,International Office Machines Ltd is looking f...,International Office Machines Ltd
4,OSS Engineer,"Dhaka, Bangladesh",On-site,Full-time,Mid-Senior level,Responsibilities：\n1. Be responsible for OSS t...,ZTE Corporation
...,...,...,...,...,...,...,...
739,MIS and Documentation Officer,"Chapai Nawabganj District, Rajshahi, Bangladesh",On-site,Full-time,NaN,Proyas Manobik Unnayan Society is looking for ...,Proyas Manobik Unnayan Society
740,Sales Analyst,"Dhaka, Bangladesh",On-site,Internship,NaN,Walton Hi-Tech Industries PLC. is looking for ...,Walton Hi-Tech Industries PLC.
741,"Full-Stack Web Developer (Laravel, React.js/Vu...","Dhaka, Bangladesh",On-site,Full-time,NaN,Arialkhan.com is looking for Full-Stack Web De...,Arialkhan.com
742,Sr. Executive / Asst. Manager - Sales & Market...,"Dhaka, Bangladesh",On-site,Full-time,NaN,Standard Design & Development Ltd. is looking ...,Standard Design & Development Ltd.
743,Service Engineer,"Dhaka, Bangladesh",On-site,Full-time,NaN,Executive Machines Ltd is looking for Service ...,Executive Machines Ltd